nome = input('Digite Seu Nome: ')
nmi = nome.lower()
nma = nome.upper()
nlet= nome.strip().split()
nomee = nome.replace(' ','')
letras = len(nomee)
letum = len(nlet [0])
print('Seu nome em minúsculo: {}'.format(nmi))
print('Seu nome em Maiúsculo: {}'.format(nma))
print('Número de letras sem contar os espaços: {}'.format(letras))
print('Número de Letras do seu primeiro nome: {}'.format(letum))
